backend:
  name: git-gateway
  branch: main 

# directory pointers
media_folder: '_site/images/uploads'
public_folder: '/images/uploads'

# portfolio collection
collections:
  - label: "Portfolio project"
    name: "portfolioItems"
    folder: "src/portfolio"
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string", pattern: ['^.{0,30}$', "Must have fewer than 30 characters"]}
      - {label: "Starred", name: "starred", widget: "boolean", default: false}
      - {label: "Cover", name: "cover", widget: "image" }
      - {label: "Content Type", name: "type", widget: "select", options: ["Article", "Video", "Project", "Newsletter", "One-pager", "Other"]}
      - {label: "Summary", name: "summary", widget: "string", pattern: ['^.{0,140}$', "Must have fewer than 140 characters"]}
      - {label: "Link", name: "link", widget: "string"}