backend:
  name: git-gateway
  branch: main 

# directory pointers
media_folder: '_site/images/uploads'
public_folder: '/images/uploads'

# portfolio collection
collections:
  - name: "portfolio"
    label: "Portfolio project"
    folder: "src/_posts/portfolio"
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Starred", name: "starred", widget: "boolean", default: false}
      - {label: "Cover", name: "cover", widget: "image" }
      - {label: "Content Type", name: "type", widget: "select", options: ["Article", "Video", "Project", "Newsletter", "One-pager", "Other"]}
      - {label: "Standalone", name: "standalone", widget: "boolean", default: true}
      - {label: "Link", name: "link", widget: "string", required: false, hint: "Required if standalone is set to false - link to the project"}
      - {label: "Content", name: "content", widget: "markdown", required: false, hint: "Required if standalone is set to true - project page"}